name: "dbt_transformation"
version: "1.0.0"
config-version: 2

profile: "dbt_transformation"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_transformation:
    staging:
      +materialized: view
    marts:
      +materialized: table
